# CAR DATASET

In [1]:
import numpy as np
import pandas as pd

In [34]:
df= pd.read_csv(r"C:\Users\Kumar Shivam\Desktop\Data science\CAR SHEET DATA.csv")

In [35]:
df.head(50)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,18,24,3880,115,197
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225,18,24,3893,115,197
6,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.2,6.0,290,17,24,3153,100,174
7,Audi,A4 1.8T 4dr,Sedan,Europe,Front,"$25,940","$23,508",1.8,4.0,170,22,31,3252,104,179
8,Audi,A41.8T convertible 2dr,Sedan,Europe,Front,"$35,940","$32,506",1.8,4.0,170,23,30,3638,105,180
9,Audi,A4 3.0 4dr,Sedan,Europe,Front,"$31,840","$28,846",3.0,6.0,220,20,28,3462,104,179
10,Audi,A4 3.0 Quattro 4dr manual,Sedan,Europe,All,"$33,430","$30,366",3.0,6.0,220,17,26,3583,104,179
11,Audi,A4 3.0 Quattro 4dr auto,Sedan,Europe,All,"$34,480","$31,388",3.0,6.0,220,18,25,3627,104,179
12,Audi,A6 3.0 4dr,Sedan,Europe,Front,"$36,640","$33,129",3.0,6.0,220,20,27,3561,109,192
13,Audi,A6 3.0 Quattro 4dr,Sedan,Europe,All,"$39,640","$35,992",3.0,6.0,220,18,25,3880,109,192
14,Audi,A4 3.0 convertible 2dr,Sedan,Europe,Front,"$42,490","$38,325",3.0,6.0,220,20,27,3814,105,180
15,Audi,A4 3.0 Quattro convertible 2dr,Sedan,Europe,All,"$44,240","$40,075",3.0,6.0,220,18,25,4013,105,180
16,Audi,A6 2.7 Turbo Quattro 4dr,Sedan,Europe,All,"$42,840","$38,840",2.7,6.0,250,18,25,3836,109,192
17,Audi,A6 4.2 Quattro 4dr,Sedan,Europe,All,"$49,690","$44,936",4.2,8.0,300,17,24,4024,109,193
18,Audi,A8 L Quattro 4dr,Sedan,Europe,All,"$69,190","$64,740",4.2,8.0,330,17,24,4399,121,204
19,Audi,S4 Quattro 4dr,Sedan,Europe,All,"$48,040","$43,556",4.2,8.0,340,14,20,3825,104,179
20,Audi,RS 6 4dr,Sports,Europe,Front,"$84,600","$76,417",4.2,8.0,450,15,22,4024,109,191
21,Audi,TT 1.8 convertible 2dr (coupe),Sports,Europe,Front,"$35,940","$32,512",1.8,4.0,180,20,28,3131,95,159
22,Audi,TT 1.8 Quattro 2dr (convertible),Sports,Europe,All,"$37,390","$33,891",1.8,4.0,225,20,28,2921,96,159
23,Audi,TT 3.2 coupe 2dr (convertible),Sports,Europe,All,"$40,590","$36,739",3.2,6.0,250,21,29,3351,96,159
24,Audi,A6 3.0 Avant Quattro,Wagon,Europe,All,"$40,840","$37,060",3.0,6.0,220,18,25,4035,109,192
25,Audi,S4 Avant Quattro,Wagon,Europe,All,"$49,090","$44,446",4.2,8.0,340,15,21,3936,104,179
26,BMW,X3 3.0i,SUV,Europe,All,"$37,000","$33,873",3.0,6.0,225,16,23,4023,110,180
27,BMW,X5 4.4i,SUV,Europe,All,"$52,195","$47,720",4.4,8.0,325,16,22,4824,111,184
28,BMW,325i 4dr,Sedan,Europe,Rear,"$28,495","$26,155",2.5,6.0,184,20,29,3219,107,176
29,BMW,325Ci 2dr,Sedan,Europe,Rear,"$30,795","$28,245",2.5,6.0,184,20,29,3197,107,177
30,BMW,325Ci convertible 2dr,Sedan,Europe,Rear,"$37,995","$34,800",2.5,6.0,184,19,27,3560,107,177
31,BMW,325xi 4dr,Sedan,Europe,All,"$30,245","$27,745",2.5,6.0,184,19,27,3461,107,176
32,BMW,330i 4dr,Sedan,Europe,Rear,"$35,495","$32,525",3.0,6.0,225,20,30,3285,107,176
33,BMW,330Ci 2dr,Sedan,Europe,Rear,"$36,995","$33,890",3.0,6.0,225,20,30,3285,107,176
34,BMW,330xi 4dr,Sedan,Europe,All,"$37,245","$34,115",3.0,6.0,225,20,29,3483,107,176
35,BMW,525i 4dr,Sedan,Europe,Rear,"$39,995","$36,620",2.5,6.0,184,19,28,3428,114,191
36,BMW,330Ci convertible 2dr,Sedan,Europe,Rear,"$44,295","$40,530",3.0,6.0,225,19,28,3616,107,177
37,BMW,530i 4dr,Sedan,Europe,Rear,"$44,995","$41,170",3.0,6.0,225,20,30,3472,114,191
38,BMW,545iA 4dr,Sedan,Europe,Rear,"$54,995","$50,270",4.4,8.0,325,18,26,3814,114,191
39,BMW,745i 4dr,Sedan,Europe,Rear,"$69,195","$63,190",4.4,8.0,325,18,26,4376,118,198
40,BMW,745Li 4dr,Sedan,Europe,Rear,"$73,195","$66,830",4.4,8.0,325,18,26,4464,123,204
41,BMW,M3 coupe 2dr,Sports,Europe,Rear,"$48,195","$44,170",3.2,6.0,333,16,24,3415,108,177
42,BMW,M3 convertible 2dr,Sports,Europe,Rear,"$56,595","$51,815",3.2,6.0,333,16,23,3781,108,177
43,BMW,Z4 convertible 2.5i 2dr,Sports,Europe,Rear,"$33,895","$31,065",2.5,6.0,184,20,28,2932,98,161
44,BMW,Z4 convertible 3.0i 2dr,Sports,Europe,Rear,"$41,045","$37,575",3.0,6.0,225,21,29,2998,98,161
45,BMW,325xi Sport,Wagon,Europe,All,"$32,845","$30,110",2.5,6.0,184,19,26,3594,107,176
46,Buick,Rainier,SUV,USA,All,"$37,895","$34,357",4.2,6.0,275,15,21,4600,113,193
47,Buick,Rendezvous CX,SUV,USA,Front,"$26,545","$24,085",3.4,6.0,185,19,26,4024,112,187
48,Buick,Century Custom 4dr,Sedan,USA,Front,"$22,180","$20,351",3.1,6.0,175,20,30,3353,109,195
49,Buick,LeSabre Custom 4dr,Sedan,USA,Front,"$26,470","$24,282",3.8,6.0,205,20,29,3567,112,200

In [36]:
df.shape

(428, 15)

### CLEANING DATA

In [37]:
#STEP 1

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 428 entries, 0 to 427
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Make         428 non-null    object
 1   Model        428 non-null    object
 2   Type         428 non-null    object
 3   Origin       428 non-null    object
 4   DriveTrain   428 non-null    object
 5   MSRP         428 non-null    object
 6   Invoice      428 non-null    object
 7   EngineSize   428 non-null    float64
 8   Cylinders    426 non-null    float64
 9   Horsepower   428 non-null    int64
 10  MPG_City     428 non-null    int64
 11  MPG_Highway  428 non-null    int64
 12  Weight       428 non-null    int64
 13  Wheelbase    428 non-null    int64
 14  Length       428 non-null    int64
dtypes: float64(2), int64(6), object(7)
memory usage: 50.3+ KB

In [61]:
df.count()

Make           428
Model          428
Type           428
Origin         428
DriveTrain     428
MSRP           428
Invoice        428
EngineSize     428
Cylinders      428
Horsepower     428
MPG_City       428
MPG_Highway    428
Weight         428
Wheelbase      428
Length         428
dtype: int64

In [39]:
df['Make'].value_counts().head(3)

Toyota           28
Chevrolet        27
Mercedes-Benz    26
Name: Make, dtype: int64

In [58]:
#for null value 
df[df.notnull()]

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,18,24,3880,115,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197,21,28,3450,105,186
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242,20,26,3450,105,186
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268,19,26,3653,110,190
426,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170,22,29,2822,101,180
427,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208,20,27,3823,109,186

In [54]:
df['Cylinders'].fillna(df['Cylinders'].mean(),inplace = True)

In [55]:
df

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,18,24,3880,115,197
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,Volvo,C70 LPT convertible 2dr,Sedan,Europe,Front,"$40,565","$38,203",2.4,5.0,197,21,28,3450,105,186
424,Volvo,C70 HPT convertible 2dr,Sedan,Europe,Front,"$42,565","$40,083",2.3,5.0,242,20,26,3450,105,186
425,Volvo,S80 T6 4dr,Sedan,Europe,Front,"$45,210","$42,573",2.9,6.0,268,19,26,3653,110,190
426,Volvo,V40,Wagon,Europe,Front,"$26,135","$24,641",1.9,4.0,170,22,29,2822,101,180
427,Volvo,XC70,Wagon,Europe,All,"$35,145","$33,112",2.5,5.0,208,20,27,3823,109,186

In [59]:
df.isnull().sum()

Make           0
Model          0
Type           0
Origin         0
DriveTrain     0
MSRP           0
Invoice        0
EngineSize     0
Cylinders      0
Horsepower     0
MPG_City       0
MPG_Highway    0
Weight         0
Wheelbase      0
Length         0
dtype: int64

In [62]:
#Q2
df.count()

Make           428
Model          428
Type           428
Origin         428
DriveTrain     428
MSRP           428
Invoice        428
EngineSize     428
Cylinders      428
Horsepower     428
MPG_City       428
MPG_Highway    428
Weight         428
Wheelbase      428
Length         428
dtype: int64

In [63]:
df['Make'].value_counts()

Toyota           28
Chevrolet        27
Mercedes-Benz    26
Ford             23
BMW              20
Audi             19
Honda            17
Nissan           17
Volkswagen       15
Chrysler         15
Dodge            13
Mitsubishi       13
Hyundai          12
Volvo            12
Jaguar           12
Subaru           11
Pontiac          11
Lexus            11
Kia              11
Mazda            11
Mercury           9
Lincoln           9
Buick             9
Cadillac          8
GMC               8
Suzuki            8
Infiniti          8
Saturn            8
Porsche           7
Saab              7
Acura             7
Jeep              3
Oldsmobile        3
Land Rover        3
Isuzu             2
MINI              2
Scion             2
Hummer            1
Name: Make, dtype: int64

In [64]:
#Q3
df.head(2)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172

In [66]:
df[(df['Origin'] == 'Asia') | (df['Origin'] == 'Europe')].head(50)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,270,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,225,18,24,3880,115,197
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,225,18,24,3893,115,197
6,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.2,6.0,290,17,24,3153,100,174
7,Audi,A4 1.8T 4dr,Sedan,Europe,Front,"$25,940","$23,508",1.8,4.0,170,22,31,3252,104,179
8,Audi,A41.8T convertible 2dr,Sedan,Europe,Front,"$35,940","$32,506",1.8,4.0,170,23,30,3638,105,180
9,Audi,A4 3.0 4dr,Sedan,Europe,Front,"$31,840","$28,846",3.0,6.0,220,20,28,3462,104,179
10,Audi,A4 3.0 Quattro 4dr manual,Sedan,Europe,All,"$33,430","$30,366",3.0,6.0,220,17,26,3583,104,179
11,Audi,A4 3.0 Quattro 4dr auto,Sedan,Europe,All,"$34,480","$31,388",3.0,6.0,220,18,25,3627,104,179
12,Audi,A6 3.0 4dr,Sedan,Europe,Front,"$36,640","$33,129",3.0,6.0,220,20,27,3561,109,192
13,Audi,A6 3.0 Quattro 4dr,Sedan,Europe,All,"$39,640","$35,992",3.0,6.0,220,18,25,3880,109,192
14,Audi,A4 3.0 convertible 2dr,Sedan,Europe,Front,"$42,490","$38,325",3.0,6.0,220,20,27,3814,105,180
15,Audi,A4 3.0 Quattro convertible 2dr,Sedan,Europe,All,"$44,240","$40,075",3.0,6.0,220,18,25,4013,105,180
16,Audi,A6 2.7 Turbo Quattro 4dr,Sedan,Europe,All,"$42,840","$38,840",2.7,6.0,250,18,25,3836,109,192
17,Audi,A6 4.2 Quattro 4dr,Sedan,Europe,All,"$49,690","$44,936",4.2,8.0,300,17,24,4024,109,193
18,Audi,A8 L Quattro 4dr,Sedan,Europe,All,"$69,190","$64,740",4.2,8.0,330,17,24,4399,121,204
19,Audi,S4 Quattro 4dr,Sedan,Europe,All,"$48,040","$43,556",4.2,8.0,340,14,20,3825,104,179
20,Audi,RS 6 4dr,Sports,Europe,Front,"$84,600","$76,417",4.2,8.0,450,15,22,4024,109,191
21,Audi,TT 1.8 convertible 2dr (coupe),Sports,Europe,Front,"$35,940","$32,512",1.8,4.0,180,20,28,3131,95,159
22,Audi,TT 1.8 Quattro 2dr (convertible),Sports,Europe,All,"$37,390","$33,891",1.8,4.0,225,20,28,2921,96,159
23,Audi,TT 3.2 coupe 2dr (convertible),Sports,Europe,All,"$40,590","$36,739",3.2,6.0,250,21,29,3351,96,159
24,Audi,A6 3.0 Avant Quattro,Wagon,Europe,All,"$40,840","$37,060",3.0,6.0,220,18,25,4035,109,192
25,Audi,S4 Avant Quattro,Wagon,Europe,All,"$49,090","$44,446",4.2,8.0,340,15,21,3936,104,179
26,BMW,X3 3.0i,SUV,Europe,All,"$37,000","$33,873",3.0,6.0,225,16,23,4023,110,180
27,BMW,X5 4.4i,SUV,Europe,All,"$52,195","$47,720",4.4,8.0,325,16,22,4824,111,184
28,BMW,325i 4dr,Sedan,Europe,Rear,"$28,495","$26,155",2.5,6.0,184,20,29,3219,107,176
29,BMW,325Ci 2dr,Sedan,Europe,Rear,"$30,795","$28,245",2.5,6.0,184,20,29,3197,107,177
30,BMW,325Ci convertible 2dr,Sedan,Europe,Rear,"$37,995","$34,800",2.5,6.0,184,19,27,3560,107,177
31,BMW,325xi 4dr,Sedan,Europe,All,"$30,245","$27,745",2.5,6.0,184,19,27,3461,107,176
32,BMW,330i 4dr,Sedan,Europe,Rear,"$35,495","$32,525",3.0,6.0,225,20,30,3285,107,176
33,BMW,330Ci 2dr,Sedan,Europe,Rear,"$36,995","$33,890",3.0,6.0,225,20,30,3285,107,176
34,BMW,330xi 4dr,Sedan,Europe,All,"$37,245","$34,115",3.0,6.0,225,20,29,3483,107,176
35,BMW,525i 4dr,Sedan,Europe,Rear,"$39,995","$36,620",2.5,6.0,184,19,28,3428,114,191
36,BMW,330Ci convertible 2dr,Sedan,Europe,Rear,"$44,295","$40,530",3.0,6.0,225,19,28,3616,107,177
37,BMW,530i 4dr,Sedan,Europe,Rear,"$44,995","$41,170",3.0,6.0,225,20,30,3472,114,191
38,BMW,545iA 4dr,Sedan,Europe,Rear,"$54,995","$50,270",4.4,8.0,325,18,26,3814,114,191
39,BMW,745i 4dr,Sedan,Europe,Rear,"$69,195","$63,190",4.4,8.0,325,18,26,4376,118,198
40,BMW,745Li 4dr,Sedan,Europe,Rear,"$73,195","$66,830",4.4,8.0,325,18,26,4464,123,204
41,BMW,M3 coupe 2dr,Sports,Europe,Rear,"$48,195","$44,170",3.2,6.0,333,16,24,3415,108,177
42,BMW,M3 convertible 2dr,Sports,Europe,Rear,"$56,595","$51,815",3.2,6.0,333,16,23,3781,108,177
43,BMW,Z4 convertible 2.5i 2dr,Sports,Europe,Rear,"$33,895","$31,065",2.5,6.0,184,20,28,2932,98,161
44,BMW,Z4 convertible 3.0i 2dr,Sports,Europe,Rear,"$41,045","$37,575",3.0,6.0,225,21,29,2998,98,161
45,BMW,325xi Sport,Wagon,Europe,All,"$32,845","$30,110",2.5,6.0,184,19,26,3594,107,176
149,Honda,Civic Hybrid 4dr manual (gas/electric),Hybrid,Asia,Front,"$20,140","$18,451",1.4,4.0,93,46,51,2732,103,175
150,Honda,Insight 2dr (gas/electric),Hybrid,Asia,Front,"$19,110","$17,911",2.0,3.0,73,60,66,1850,95,155
151,Honda,Pilot LX,SUV,Asia,All,"$27,560","$24,843",3.5,6.0,240,17,22,4387,106,188
152,Honda,CR-V LX,SUV,Asia,All,"$19,860","$18,419",2.4,4.0,160,21,25,3258,103,179

In [67]:
#q4  removing rows

df.head(3)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
0,Acura,MDX,SUV,Asia,All,"$36,945","$33,337",3.5,6.0,265,17,23,4451,106,189
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,200,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,200,22,29,3230,105,183

In [76]:
df = df[~(df['Weight']>4000)]
df.head

In [77]:
df.shape

(325, 15)

In [78]:
#Q5

df['Horsepower'] = df['Horsepower'].apply(lambda x:x+2)

<ipython-input-78-f9fd99eb80d1>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Horsepower'] = df['Horsepower'].apply(lambda x:x+2)

In [83]:
df.head(15)

,Make,Model,Type,Origin,DriveTrain,MSRP,Invoice,EngineSize,Cylinders,Horsepower,MPG_City,MPG_Highway,Weight,Wheelbase,Length
1,Acura,RSX Type S 2dr,Sedan,Asia,Front,"$23,820","$21,761",2.0,4.0,202,24,31,2778,101,172
2,Acura,TSX 4dr,Sedan,Asia,Front,"$26,990","$24,647",2.4,4.0,202,22,29,3230,105,183
3,Acura,TL 4dr,Sedan,Asia,Front,"$33,195","$30,299",3.2,6.0,272,20,28,3575,108,186
4,Acura,3.5 RL 4dr,Sedan,Asia,Front,"$43,755","$39,014",3.5,6.0,227,18,24,3880,115,197
5,Acura,3.5 RL w/Navigation 4dr,Sedan,Asia,Front,"$46,100","$41,100",3.5,6.0,227,18,24,3893,115,197
6,Acura,NSX coupe 2dr manual S,Sports,Asia,Rear,"$89,765","$79,978",3.2,6.0,292,17,24,3153,100,174
7,Audi,A4 1.8T 4dr,Sedan,Europe,Front,"$25,940","$23,508",1.8,4.0,172,22,31,3252,104,179
8,Audi,A41.8T convertible 2dr,Sedan,Europe,Front,"$35,940","$32,506",1.8,4.0,172,23,30,3638,105,180
9,Audi,A4 3.0 4dr,Sedan,Europe,Front,"$31,840","$28,846",3.0,6.0,222,20,28,3462,104,179
10,Audi,A4 3.0 Quattro 4dr manual,Sedan,Europe,All,"$33,430","$30,366",3.0,6.0,222,17,26,3583,104,179
11,Audi,A4 3.0 Quattro 4dr auto,Sedan,Europe,All,"$34,480","$31,388",3.0,6.0,222,18,25,3627,104,179
12,Audi,A6 3.0 4dr,Sedan,Europe,Front,"$36,640","$33,129",3.0,6.0,222,20,27,3561,109,192
13,Audi,A6 3.0 Quattro 4dr,Sedan,Europe,All,"$39,640","$35,992",3.0,6.0,222,18,25,3880,109,192
14,Audi,A4 3.0 convertible 2dr,Sedan,Europe,Front,"$42,490","$38,325",3.0,6.0,222,20,27,3814,105,180
16,Audi,A6 2.7 Turbo Quattro 4dr,Sedan,Europe,All,"$42,840","$38,840",2.7,6.0,252,18,25,3836,109,192

In [84]:
####doone###